### ISSUE TITLE
Save result of pixel_overlaps

### ISSUE THREAD

**Issue by rmcd-mscb** [ks905383/xagg#11]
Thanks for the excellent package.  Can you recommend a method for saving the result of the pixel_overlaps()?  Working with a very large shapefile with approximately 110K polygons and would like to not recalculate the weights :).  Thanks Again!

**Comment by ks905383** [comment]
Yeah, I can definitely see why you'd want to save the output from `pixel_overlaps()`! 

I think this should be feasible, though a little clunky - the output to `pixel_overlaps()` contains four items: 
- `agg`: a `pd.DataFrame` with each element of the input polygon + the pixels that overlap it (and by how much)
- `source_grid`: a dictionary with elements `lat`, `lon` giving `xr.DataArray`s for the input lat/lon grid 
- `geometry`: a `gpd.GeoDataFrame` with the input polygon geometric information (though this could be combined with `agg` above)
- `weights`: inputted weights (`xarray` structure) or 'nowghts' if no weights are inputted. 

So, three or four files (one, two csvs, one or two netcdfs) will have to be saved to keep all the information the same (through something like `weightmap.save()`). A wrinkle is that `to_csv()` is not commutative for these data frames (i.e. `pd.read_csv(a.to_csv) != a` to use somewhat pseudo-y code), so some pre-processing would have to be done to reload that information.  

To make this easier, maybe the way to go would be to take a page out of the shapefile book, and save a set of 4 files, each with the same name but a different suffix. Then, one could input a filename into `aggregate()` instead of a `weightmap` class object, and the code would just automatically load those four files, put them into the right order, and then continue with the processing of `aggregate()`. 

Or maybe there's a way to cut down on the information that `xa.aggregate()` needs. I'll think on it, and hopefully will be able to look at this soon!

**Comment by rmcd-mscb** [comment]
Thanks!  I was able to use pickle to save and load the result of pixel_overlaps().  For information that binary pickle file is over 3Gb :) So if there is a minimal set of information required by aggregate() that would be super great. The aggragate function is super fast!  

Off topic - wondering if you have worked with any curvilinear grids?  

Thanks Kevin

**Comment by ks905383** [comment]
Yikes, that's a lot!

Could you actually point me to the shapefile you're using (or one of similar complexity)? That'll make it easier to optimize.

**Comment by ks905383** [comment]
Re: curvilinear grids - personally, yes - through `xagg`; no. I think the core functions should work with them, but there might be some housekeeping around them that might not quite work. 

Maybe we could build a test for aggregating of a curvilinear grid to see if it works/or what needs to happen for it to work!

**Comment by rmcd-mscb** [comment]
Here is a couple examples of shapefiles including CONUS and smaller regional scale.  Example netcdf file as well.  

https://drive.google.com/file/d/1t4ssRyt5L5zqCyAnqdc_SVM_Rs5fY0ri/view?usp=sharing

**Comment by ks905383** [comment]
Ok an implementation is drafted in https://github.com/ks905383/xagg/tree/save_pixel_overlaps - would love any comments! 

Basically, the output of `pixel_overlaps()` is saved as a series of files in a new directory using `wm.export_weightmap(fn)` that are then read though `xa.read_wm()`. The directory and all the files share the same name (the files of course with relevant suffixes). `fn` can be a path, in which case the "file"name of the individual files (and the directory) is taken as the last segment of the path. 

The one thing that I'm mildly worried about is some `hd5` errors that showed up until I reinstalled `hd5` from scratch, and a potentially bad `tables` version installed by some other `xagg` dependencies.

**Comment by rmcd-mscb** [comment]
Hey Kevin, Thanks for working on this and sorry it took me a while to check it out.  I tried saving the weights working with the save_pixel_overlaps branch and It only wrote the shp file.  

`weightmap = xa.pixel_overlaps(ds, gdf)`
`weightmap.to_file('../wm_nhru_1a', overwrite=True)`

resulted in:
wm_nhru_1a/
     wm_nhru_1a.cpg
     wm_nhru_1a.dbf
     wm_nhru_1a.prj
     wm_nhru_1a.shp
     wm_nhru_1a.shx

**Comment by ks905383** [comment]
I _think_ I've fixed that with the latest commit on that branch that I just pushed, could you verify?

**Comment by rmcd-mscb** [comment]
Thanks Kevin - I took a look. Can you please give a short example of how you would use the 2 new functions.  Here is what I did which resulted in an error: 
`
start = time.perf_counter()
weightmap = xa.pixel_overlaps(ds_tmax_1,gdf)
end = time.perf_counter()
print(f'finished agg in {round(end-start, 2)} second(s)')
weightmap.to_file('weightmap.file')

wm2 = xa.core.read_wm('weightmap.file')
aggr = xa.aggregate(ds_tmax_1, wm2)
`

Files saved as:
![image](https://user-images.githubusercontent.com/11791580/161438042-b5b51764-9373-45c9-8b0f-09e1d7878a94.png)


error: DriverError: weightmap.file/weightmap.file.shp: No such file or directory

**Comment by rmcd-mscb** [comment]
Saving to 'weightmap_file' works, really you are saving to a folder.

**Comment by ks905383** [comment]
Right, yeah, maybe it needs to be clearer to specify that the input filename will be the name of the directory and the files _without_ the filename extension (and maybe a warning if someone passes a filename with an extension already)

**Comment by rmcd-mscb** [comment]
Thanks Kevin

**Comment by ks905383** [comment]
Docs now specify that you create a _directory_ with `wm.to_file()` instead of a file.
