### ISSUE TITLE
pixel_overlaps updates input geodataframe

### ISSUE THREAD

**Issue by raybellwaves** [ks905383/xagg#21]
I'm not sure if it is desired. From a user point I wouldn't expect an argument to get updated when it's input into a function.

<img width="610" alt="Screen Shot 2021-09-21 at 9 36 44 PM" src="https://user-images.githubusercontent.com/17162724/134269716-5c0a9c1d-748f-41e6-9985-d986329d6396.png">

**Comment by ks905383** [comment]
yeesh, that's not great. 

Maybe a `copy.deepcopy()` is necessary... (once again frustrated at the ambiguous way that python seems to run workspaces - though I think this may be more of a jupyter issue? I think that in notebooks to make variables work across cells, they're generally declared globally by the backend even if they shouldn't be (i.e., they're inside functions), but since notebooks are a common tool, that should be accounted for).

I'll add it to the to-do list.
