### ISSUE TITLE
Trying to install outside target directory

### ISSUE THREAD

**Issue by konradhafen** [ks905383/xagg#23]
Get this error when trying to install with pip on windows. Have tried to install from pypi, github, and zip. Same error in each instance. I've tried with a base python install using virtual env and with conda.
`ERROR: The zip file (C:\Users\profile\Downloads\xagg-main.zip) has a file (C:\Users\khafen\AppData\Local\Temp\3\pip-req-build-cok0yin6\xagg/aux.py) trying to install outside target directory (C:\Users\profile\AppData\Local\Temp\3\pip-req-build-cok0yin6)`

**Comment by ks905383** [comment]
I think this is because `aux` is a protected filename in windows (this was just brought up in #22 as well). I'd only ever tested this on linux/Mac systems so I hadn't run into this. 

I'll make sure that the next release (hopefully coming soon) will just rename `aux` to, e.g., `aux_funcs`. I _think_ that should fix the problem, but it'll be good to get a test from someone on a windows machine at that point.

**Comment by RichardScottOZ** [comment]
Yes, saw this too and started to suspect never been used on windows having failed a few times and variations.

**Comment by ks905383** [comment]
May be fixed now in the latest version [v0.3.2.0](https://github.com/ks905383/xagg/releases/tag/v0.3.2.0). Let me know if you still have issues!
